In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv(r"C:\Users\JahnaviP\Downloads\Fish.csv")

In [3]:
data.head(1)

Species  Weight  Length1  Length2  Length3  Height  Width
0   Bream   242.0     23.2     25.4     30.0   11.52   4.02

In [4]:
data.isnull().any()

Species    False
Weight     False
Length1    False
Length2    False
Length3    False
Height     False
Width      False
dtype: bool

In [5]:
data.Species.unique()

array(['Bream', 'Roach', 'Whitefish', 'Parkki', 'Perch', 'Pike', 'Smelt'],
      dtype=object)

In [6]:
x=data.iloc[:,1:7].values
y=data.iloc[:,0:1].values

In [7]:
y

array([['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Bream'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['Roach'],
       ['W

In [8]:
y.ndim

2

In [9]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(y[:,0:1]).toarray()
y = np.delete(y,0,axis = 1)
y = np.concatenate((z,y),axis = 1)


In [10]:
y

array([[1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0]], dtype=object)

In [11]:
print(y)

[[1.0 0.0 0.0 ... 0.0 0.0 0.0]
 [1.0 0.0 0.0 ... 0.0 0.0 0.0]
 [1.0 0.0 0.0 ... 0.0 0.0 0.0]
 ...
 [0.0 0.0 0.0 ... 0.0 1.0 0.0]
 [0.0 0.0 0.0 ... 0.0 1.0 0.0]
 [0.0 0.0 0.0 ... 0.0 1.0 0.0]]


In [12]:
import tensorflow as tf
print(tf.__version__)

1.14.0


In [13]:
z

array([[1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 1., 0.]])

In [14]:
y.shape

(159, 7)

In [15]:
y

array([[1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       [1.0, 0.0, 0.0, ..., 0.0, 0.0, 0.0],
       ...,
       [0.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0],
       [0.0, 0.0, 0.0, ..., 0.0, 1.0, 0.0]], dtype=object)

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [17]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.fit_transform(x_test)

In [18]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [19]:
cat=Sequential()

In [20]:
cat.add(Dense(6,kernel_initializer="random_uniform",activation="relu"))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [21]:
cat.add(Dense(12,kernel_initializer="random_uniform",activation="relu"))

In [22]:
cat.add(Dense(7,kernel_initializer="random_uniform",activation="softmax"))

In [23]:
cat.compile("adam","categorical_crossentropy",metrics=["accuracy"])

In [24]:
cat.fit(x_train,y_train,batch_size=32,epochs=700)

Epoch 1/700
127/127 [==============================] - 1s 5ms/sample - loss: 1.9451 - acc: 0.2598
Epoch 2/700
127/127 [==============================] - 0s 162us/sample - loss: 1.9425 - acc: 0.3701
Epoch 3/700
127/127 [==============================] - 0s 112us/sample - loss: 1.9399 - acc: 0.3701
Epoch 4/700
127/127 [==============================] - 0s 109us/sample - loss: 1.9371 - acc: 0.3701
Epoch 5/700
127/127 [==============================] - 0s 73us/sample - loss: 1.9344 - acc: 0.3701
Epoch 6/700
127/127 [==============================] - 0s 90us/sample - loss: 1.9311 - acc: 0.3701
Epoch 7/700
127/127 [==============================] - 0s 97us/sample - loss: 1.9279 - acc: 0.3701
Epoch 8/700
127/127 [==============================] - 0s 66us/sample - loss: 1.9242 - acc: 0.3701
Epoch 9/700
127/127 [==============================] - 0s 138us/sample - loss: 1.9196 - acc: 0.3701
Epoch 10/700
127/127 [==============================] - 0s 125us/sample - loss: 1.9145 - acc: 0.3701
Epoch

Epoch 82/700
127/127 [==============================] - 0s 46us/sample - loss: 1.2441 - acc: 0.5591
Epoch 83/700
127/127 [==============================] - 0s 66us/sample - loss: 1.2424 - acc: 0.5512
Epoch 84/700
127/127 [==============================] - 0s 120us/sample - loss: 1.2407 - acc: 0.5512
Epoch 85/700
127/127 [==============================] - 0s 60us/sample - loss: 1.2392 - acc: 0.5512
Epoch 86/700
127/127 [==============================] - 0s 69us/sample - loss: 1.2373 - acc: 0.5512
Epoch 87/700
127/127 [==============================] - 0s 59us/sample - loss: 1.2359 - acc: 0.5433
Epoch 88/700
127/127 [==============================] - 0s 118us/sample - loss: 1.2340 - acc: 0.5512
Epoch 89/700
127/127 [==============================] - 0s 52us/sample - loss: 1.2323 - acc: 0.5512
Epoch 90/700
127/127 [==============================] - 0s 58us/sample - loss: 1.2306 - acc: 0.5512
Epoch 91/700
127/127 [==============================] - 0s 98us/sample - loss: 1.2294 - acc: 0.559

Epoch 163/700
127/127 [==============================] - 0s 69us/sample - loss: 1.1456 - acc: 0.5512
Epoch 164/700
127/127 [==============================] - 0s 141us/sample - loss: 1.1446 - acc: 0.5512
Epoch 165/700
127/127 [==============================] - 0s 67us/sample - loss: 1.1438 - acc: 0.5512
Epoch 166/700
127/127 [==============================] - 0s 94us/sample - loss: 1.1428 - acc: 0.5512
Epoch 167/700
127/127 [==============================] - 0s 125us/sample - loss: 1.1417 - acc: 0.5512
Epoch 168/700
127/127 [==============================] - 0s 122us/sample - loss: 1.1408 - acc: 0.5512
Epoch 169/700
127/127 [==============================] - 0s 78us/sample - loss: 1.1397 - acc: 0.5512
Epoch 170/700
127/127 [==============================] - 0s 58us/sample - loss: 1.1387 - acc: 0.5512
Epoch 171/700
127/127 [==============================] - 0s 64us/sample - loss: 1.1381 - acc: 0.5512
Epoch 172/700
127/127 [==============================] - 0s 56us/sample - loss: 1.1370 -

127/127 [==============================] - 0s 46us/sample - loss: 1.0628 - acc: 0.5512
Epoch 244/700
127/127 [==============================] - 0s 101us/sample - loss: 1.0608 - acc: 0.5512
Epoch 245/700
127/127 [==============================] - 0s 133us/sample - loss: 1.0587 - acc: 0.5512
Epoch 246/700
127/127 [==============================] - 0s 137us/sample - loss: 1.0577 - acc: 0.5512
Epoch 247/700
127/127 [==============================] - 0s 140us/sample - loss: 1.0560 - acc: 0.5512
Epoch 248/700
127/127 [==============================] - 0s 109us/sample - loss: 1.0543 - acc: 0.5512
Epoch 249/700
127/127 [==============================] - 0s 57us/sample - loss: 1.0526 - acc: 0.5512
Epoch 250/700
127/127 [==============================] - 0s 89us/sample - loss: 1.0512 - acc: 0.5512
Epoch 251/700
127/127 [==============================] - 0s 144us/sample - loss: 1.0491 - acc: 0.5512
Epoch 252/700
127/127 [==============================] - 0s 184us/sample - loss: 1.0473 - acc: 0.55

Epoch 324/700
127/127 [==============================] - 0s 63us/sample - loss: 0.8178 - acc: 0.6693
Epoch 325/700
127/127 [==============================] - 0s 97us/sample - loss: 0.8142 - acc: 0.6693
Epoch 326/700
127/127 [==============================] - 0s 81us/sample - loss: 0.8106 - acc: 0.6850
Epoch 327/700
127/127 [==============================] - 0s 79us/sample - loss: 0.8069 - acc: 0.7087
Epoch 328/700
127/127 [==============================] - 0s 57us/sample - loss: 0.8032 - acc: 0.7402
Epoch 329/700
127/127 [==============================] - 0s 75us/sample - loss: 0.8003 - acc: 0.7402
Epoch 330/700
127/127 [==============================] - 0s 122us/sample - loss: 0.7962 - acc: 0.7402
Epoch 331/700
127/127 [==============================] - 0s 89us/sample - loss: 0.7923 - acc: 0.7402
Epoch 332/700
127/127 [==============================] - 0s 78us/sample - loss: 0.7885 - acc: 0.7559
Epoch 333/700
127/127 [==============================] - 0s 128us/sample - loss: 0.7853 - 

127/127 [==============================] - 0s 54us/sample - loss: 0.5888 - acc: 0.7717
Epoch 405/700
127/127 [==============================] - 0s 84us/sample - loss: 0.5868 - acc: 0.7795
Epoch 406/700
127/127 [==============================] - 0s 100us/sample - loss: 0.5850 - acc: 0.7795
Epoch 407/700
127/127 [==============================] - 0s 91us/sample - loss: 0.5822 - acc: 0.7795
Epoch 408/700
127/127 [==============================] - 0s 80us/sample - loss: 0.5799 - acc: 0.7795
Epoch 409/700
127/127 [==============================] - 0s 82us/sample - loss: 0.5780 - acc: 0.7795
Epoch 410/700
127/127 [==============================] - 0s 75us/sample - loss: 0.5752 - acc: 0.7795
Epoch 411/700
127/127 [==============================] - 0s 64us/sample - loss: 0.5732 - acc: 0.7795
Epoch 412/700
127/127 [==============================] - 0s 44us/sample - loss: 0.5703 - acc: 0.7795
Epoch 413/700
127/127 [==============================] - 0s 102us/sample - loss: 0.5685 - acc: 0.7717
Ep

127/127 [==============================] - 0s 121us/sample - loss: 0.4158 - acc: 0.8425
Epoch 485/700
127/127 [==============================] - 0s 137us/sample - loss: 0.4146 - acc: 0.8425
Epoch 486/700
127/127 [==============================] - 0s 96us/sample - loss: 0.4131 - acc: 0.8425
Epoch 487/700
127/127 [==============================] - 0s 94us/sample - loss: 0.4117 - acc: 0.8425
Epoch 488/700
127/127 [==============================] - 0s 63us/sample - loss: 0.4099 - acc: 0.8425
Epoch 489/700
127/127 [==============================] - 0s 70us/sample - loss: 0.4085 - acc: 0.8425
Epoch 490/700
127/127 [==============================] - 0s 194us/sample - loss: 0.4086 - acc: 0.8425
Epoch 491/700
127/127 [==============================] - 0s 96us/sample - loss: 0.4061 - acc: 0.8425
Epoch 492/700
127/127 [==============================] - 0s 92us/sample - loss: 0.4048 - acc: 0.8425
Epoch 493/700
127/127 [==============================] - 0s 108us/sample - loss: 0.4038 - acc: 0.8425


127/127 [==============================] - 0s 51us/sample - loss: 0.3333 - acc: 0.8504
Epoch 566/700
127/127 [==============================] - 0s 70us/sample - loss: 0.3322 - acc: 0.8504
Epoch 567/700
127/127 [==============================] - 0s 75us/sample - loss: 0.3311 - acc: 0.8504
Epoch 568/700
127/127 [==============================] - 0s 50us/sample - loss: 0.3300 - acc: 0.8504
Epoch 569/700
127/127 [==============================] - 0s 57us/sample - loss: 0.3296 - acc: 0.8504
Epoch 570/700
127/127 [==============================] - 0s 90us/sample - loss: 0.3287 - acc: 0.8504
Epoch 571/700
127/127 [==============================] - 0s 57us/sample - loss: 0.3279 - acc: 0.8583
Epoch 572/700
127/127 [==============================] - 0s 68us/sample - loss: 0.3276 - acc: 0.8504
Epoch 573/700
127/127 [==============================] - ETA: 0s - loss: 0.3782 - acc: 0.812 - 0s 86us/sample - loss: 0.3274 - acc: 0.8583
Epoch 574/700
127/127 [==============================] - 0s 84us/sa

127/127 [==============================] - 0s 82us/sample - loss: 0.2806 - acc: 0.8740
Epoch 646/700
127/127 [==============================] - 0s 62us/sample - loss: 0.2803 - acc: 0.8740
Epoch 647/700
127/127 [==============================] - 0s 115us/sample - loss: 0.2795 - acc: 0.8740
Epoch 648/700
127/127 [==============================] - 0s 88us/sample - loss: 0.2789 - acc: 0.8740
Epoch 649/700
127/127 [==============================] - 0s 97us/sample - loss: 0.2786 - acc: 0.8740
Epoch 650/700
127/127 [==============================] - 0s 122us/sample - loss: 0.2781 - acc: 0.8740
Epoch 651/700
127/127 [==============================] - 0s 109us/sample - loss: 0.2784 - acc: 0.8740
Epoch 652/700
127/127 [==============================] - 0s 81us/sample - loss: 0.2772 - acc: 0.8740
Epoch 653/700
127/127 [==============================] - 0s 86us/sample - loss: 0.2765 - acc: 0.8740
Epoch 654/700
127/127 [==============================] - 0s 76us/sample - loss: 0.2762 - acc: 0.8740
E

In [25]:
ypred=cat.predict(x_test)

In [26]:
ypred   # softmax gives the probability of 90

array([[9.80294108e-01, 1.47652645e-02, 2.59659282e-06, 1.03043603e-04,
        6.23003143e-06, 1.18206442e-21, 4.82882466e-03],
       [4.04343957e-13, 1.17047383e-02, 5.63191891e-01, 2.58714207e-15,
        4.22026694e-01, 1.41864712e-03, 1.65806594e-03],
       [3.47361246e-13, 9.98290605e-04, 8.08534920e-01, 5.06085516e-14,
        1.59830585e-01, 2.99105160e-02, 7.25696853e-04],
       [5.96434430e-11, 2.31410060e-02, 4.68638718e-01, 1.05480089e-12,
        5.02455771e-01, 3.96145973e-04, 5.36829792e-03],
       [8.65380187e-03, 1.62906125e-02, 6.66126013e-01, 5.65802772e-03,
        1.28030488e-02, 5.88565605e-08, 2.90468514e-01],
       [8.89315968e-04, 6.11487252e-04, 9.20817435e-01, 4.12061112e-04,
        2.38595952e-04, 8.57431626e-10, 7.70310760e-02],
       [1.27699867e-01, 3.50132026e-02, 3.15812230e-01, 4.29561222e-03,
        2.16818554e-03, 3.10007159e-11, 5.15010834e-01],
       [1.77394191e-03, 3.24843095e-05, 3.54314357e-01, 6.07872188e-01,
        5.58130887e-05, 1

In [27]:
ypred[0]

array([9.80294108e-01, 1.47652645e-02, 2.59659282e-06, 1.03043603e-04,
       6.23003143e-06, 1.18206442e-21, 4.82882466e-03], dtype=float32)

In [28]:
y_test[0]

array([1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], dtype=object)

In [29]:
ypred[2]

array([3.4736125e-13, 9.9829060e-04, 8.0853492e-01, 5.0608552e-14,
       1.5983059e-01, 2.9910516e-02, 7.2569685e-04], dtype=float32)

In [30]:
y_test[2]

array([0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0], dtype=object)

In [31]:
cat.predict(sc.transform([[450,26.8,29.7,34.7,13.6024,4.9274]]))

array([[9.7707486e-01, 2.1533389e-02, 1.3004487e-07, 3.2437508e-06,
        1.3344511e-06, 1.7906886e-24, 1.3871341e-03]], dtype=float32)

In [32]:
cat.predict_classes(sc.transform([[450,26.8,29.7,34.7,13.6024,4.9274]]))

array([0], dtype=int64)